---
configure_osx: true
configure_ohmyzsh: true
configure_starship: true
configure_uv: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: ["Launchpad", "TV", "Podcasts", "App Store", "Reminders", "Notes", "Freeform", "Siri", "Music", "Facetime", "Photos", "Messages", "Mail"]
dockitems_persist: ["Firefox", "Visual Studio Code", "Ghostty"]
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  - git
  - gh
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - pngpaste
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - pipx
  - r
  - neovim
  - dockutil
  - kubectl
  - k9s
  - fzf
  - fd

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: true
homebrew_cask_apps:
  - 1password
  - alacritty
  - bitwarden
  - firefox
  - font-iosevka-nerd-font
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - slack
  - visual-studio-code
  - qgis
  - raycast
  - rectangle
  - rstudio
  - betterdisplay
  - zotero
  - scroll-reverser
  - ghostty
  - awscli
  - bruno
  - ticktick
  - headlamp

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
pip_packages:
  - mlflow
  - dvc[s3]
  - cookiecutter
  - locust
  - poethepoet
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
